# This file was generated by GoReleaser. DO NOT EDIT.
cask "civitai-manager" do
  version "0.1.78"

  on_macos do
    on_intel do
      sha256 "8baf93b1a2395284253b99faf28dfa25b37d5f878145dd94be224dd6b0d11470"
      url "https://github.com/ZacxDev/civitai-manager/releases/download/v#{version}/civitai-manager_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d3a95a30f37ef97f70ea408cbf81272c849307c57411a716acf5bb9d50ea5e5"
      url "https://github.com/ZacxDev/civitai-manager/releases/download/v#{version}/civitai-manager_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3d6c625aeb1c3d5f41159cbf7c36ab24025e7e79c53d711fa9e782ba55a29342"
      url "https://github.com/ZacxDev/civitai-manager/releases/download/v#{version}/civitai-manager_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b41f4b6b90ef0ea558f2b93d638e250499c4efe4a8d7d34e6aed59b480490a29"
      url "https://github.com/ZacxDev/civitai-manager/releases/download/v#{version}/civitai-manager_#{version}_linux_arm64.tar.gz"
    end
  end

  name "civitai-manager"
  desc "Subscribe to CivitAI models/creators and auto-download new versions"
  homepage "https://github.com/ZacxDev/civitai-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "civitai-manager"

  postflight do
    if OS.mac? && File.executable?("/usr/bin/xattr")
      system_command "/usr/bin/xattr",
                     args:         ["-dr", "com.apple.quarantine", staged_path],
                     must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The release binaries are not notarized by Apple, so macOS would refuse to
    run this one after Homebrew quarantines it. This cask therefore removes the
    com.apple.quarantine attribute from the files it installed — the same thing
    `brew install --no-quarantine` used to do, before Homebrew removed that flag.

    Only the files from this cask are affected. If you would rather not have
    that happen, install from a release tarball instead:
    https://github.com/ZacxDev/civitai-manager/blob/main/docs/install.md
  EOS
end
